### ISSUE TITLE
Don't depend on DB libraries

### ISSUE THREAD

**Issue by Dreamsorcerer** [Arfey/aiohttp_admin2#5]
Hey, I was just playing with aiohttp-admin and considering reviving the project, but it appears you've already started on this, so I'll try and help you out here.

First issue I noticed after installing though, is that the library depends on motor, umongo, aiomysql, sqlalchemy etc.

These should be imported conditionally and not listed as a requirement if the user does not want to use those backends.

**Comment by Arfey** [comment]
Good news. any help are welcome 🙂

Yes, you are right. all engines must be optional

**Comment by Dreamsorcerer** [comment]
Hey, so I ended up deciding to pick up the react-admin migration in aiohttp-admin, and completely rewrote that library (https://github.com/aio-libs/aiohttp_admin).
I went this way as the approach allows me to push a lot of the maintenance work upstream to react-admin (JS code in the repo is currently <200 lines) and I was able to create a simple API which allows users to create a fully functioning admin in a few lines of code, automated by inspecting SQLAlchemy models.

I haven't created examples yet, but this is the full integration code being used in a real application (Rhyme/RhymeUS are sqlalchemy models):
```
class DummyAuthPolicy(AbstractAuthorizationPolicy):
    async def authorized_userid(self, identity: str) -> Optional[str]:
        return identity if identity == "admin" else None

    async def permits(self, identity: Optional[str], permission: Union[str, Enum], context: object = None) -> bool:
        return identity == "admin"

async def check_credentials(app: ChainMapProxy, username: str, password: str) -> bool:
    return username == "admin" and password == "admin"

async def identity_callback(request: web.Request, identity: str) -> aiohttp_admin.UserDetails:
    return {"fullName": "Admin", "permissions": tuple(aiohttp_admin.Permissions)}

def setup(app: web.Application, db_engine: AsyncEngine) -> None:
    schema = {
        "security": {
            "check_credentials": check_credentials,
            "identity_callback": identity_callback,
            "secure": not app["config"]["dev"]
        },
        "resources": (
            {"model": SAResource(db_engine, Rhyme), "display": ("id", "term"), "repr": "term"},
            {"model": SAResource(db_engine, RhymeUS), "display": ("id", "term"), "repr": "term"}
        )
    }
    aiohttp_admin.setup(app, schema, DummyAuthPolicy())
```

So, I'm going to close this issue.

**Comment by Arfey** [comment]
a few lines of code is good, but when you need to customize your page and add some extra stuff (like action buttons or something like that) with react-admin it will be hard to implement

- what about show image or files
- what about upload files
- what about plugins or extensions? (add other editor or input with map to select location)
- what about smart permission (show only some part of items for current user not all)

as a simple view and crud for your data react admin it's ok, but i don't see any difference with previous solution with angular admin (with auto generated js file)

**Comment by Dreamsorcerer** [comment]
> a few lines of code is good, but when you need to customize your page and add some extra stuff (like action buttons or something like that) with react-admin it will be hard to implement

It's early days, but it's all achievable. Either by adding customisation code to aiohttp-admin, or by allowing a custom admin.js to be loaded, so users can write their own react-admin interface.

But, my main goal is to give a fully featured, fairly flexible admin interface without complex configuration. A highly customisable interface is not a goal (and I suspect anyone looking at that level of customisation will likely want to implement a custom admin anyway, rather than bootstrapping it from a library).

>     * what about show image or files
>     * what about upload files

These should be achievable, and I'll need them in my next project, so they should happen soon enough.

>     * what about plugins or extensions? (add other editor or input with map to select location)

Probably a non-goal as mentioned above. There are several different input widgets (and properties to alter them) that can be used in react-admin. If there's no map widget in react-admin, we can probably atleast view a map the same way as images (and maybe ask react-admin if they want to introduce a widget...).

>     * what about smart permission (show only some part of items for current user not all)

I think this is already handled by react-admin, but will need to try out customising it (it's why there are permissions in the auth code).

>     * what about validation (custom and default validation) and show error related to some problem field

I think react-admin widgets do some validation, and error messages from the API will be displayed, so further validation can happen there. Probably something that needs to be tested and documented though.

> but i don't see any difference with previous solution with angular admin (with auto generated js file)

I believe react-admin is the new version of that project, so it is just an evolution of that project.

The real difference is a massively simplified approach to using it. The JS code is <200 lines, while achieving everything the original did in something like 1000 lines (massively reducing the amount of maintenance with regards to using future versions of react-admin). It also doesn't need any JS from the user and is more straightforward to setup (the demos in the original look like they needed ~200 lines of JS and some other Python-side config to do what I'm now doing with just `SAResource(MyModel)`).

It also works generically with sqlalchemy, no database-specific backends.

**Comment by Arfey** [comment]
Thanks for the long answer.

Could you explain why you decided to rewrite everything from scratch instead of improving the existing library (aiohttp_admin2)? The current library already has all the features described above.

I understand that we can implement some functions with react-admin without any problems, but I'm afraid that some of them will not be as simple as you expect. Also, I'm not sure your configuration will look that simple after all the features are implemented (since now aiohttp_admin is just a simple CRUD API).

**Comment by Arfey** [comment]
> I still feel like most developers wanting something more complex will likely just build a custom application

I think so people who use flask-admin and Django admin will disagree with u

differents

```python
class UserMapper(PostgresMapperGeneric, table=users): pass

@postgres_injector.inject
class UserController(PostgresController, table=users):
    mapper = UserMapper
    inline_fields = ['id', 'term', ]

class UserView(ControllerView):
    controller = UserController
```

vs

```python
SAResource(db_engine, Rhyme), "display": ("id", "term"), "repr": "term"}
```

ok as you wish 😌 I was just trying to save your time

**Comment by Dreamsorcerer** [comment]
In the slim chance you're interested, I've been working on the project on and off over the year, while using it for 2 client projects. Still needs some tidying up and documentation, but it's been working rather well so far.

Regarding your previous points:

Images/files are still pending (haven't needed them just yet).

For plugins/extensions, we can allow custom react components to be included. Although, I've not quite found a solution I'm happy with just yet (it seems to be impossible to create reusable react components in a dynamically loaded module).

For permissions, I've added fine-grained permissions to the library, so you can specify permissions down to the row, with filters that allow, for example, a user to view a list of books only if they are of a certain genre, and only be able to see the price of each book if they are from a certain author (or anything similarly complex). e.g. https://github.com/aio-libs/aiohttp-admin/blob/master/examples/permissions.py#L102-L123

For validation, you can obviously add validation on the backend. On the frontend, this is also easy, as you just create validation functions in a JS module and can then reference them in the schema. e.g. https://github.com/aio-libs/aiohttp-admin/blob/master/examples/validators.py#L16-L22

**Comment by Arfey** [comment]
thx. current library cover all my cases without any extra work.
