### ISSUE TITLE
Error after initial setup

### ISSUE THREAD

**Issue by Dreamsorcerer** [Arfey/aiohttp_admin2#6]
Following the docs, after the initial setup (which only involves `setup_admin(app)`, I then get `aiohttp_admin2.views.aiohttp.exceptions.NotRegisterView` when trying to view `/admin/` (I also get a 404 at `/admin`...).

**Comment by Arfey** [comment]
Hi. Could you add simple snippets of code for reproducing a problem 🙂

**Comment by Dreamsorcerer** [comment]
I'm adding it to an existing app, but I've literally only added `aiohttp_admin2.setup_admin(app)` so far. The documentation says this should work: https://aiohttp-admin2.readthedocs.io/#quick-start

**Comment by Dreamsorcerer** [comment]
I can see that `views` is an empty list: https://github.com/Arfey/aiohttp_admin2/blob/master/aiohttp_admin2/views/aiohttp/views/base.py#L261

**Comment by Arfey** [comment]
Hm, i can't to reproduce an issues. All work fine with simple setup

```
from aiohttp import web
from aiohttp_admin2 import setup_admin

app = web.Application()

# setup admin interface
setup_admin(app)

web.run_app(app)
```

current code works for u?

**Comment by Dreamsorcerer** [comment]
Something is not setup correctly. It does not work when run under aiohttp-devtools.

Change code to:
```
from aiohttp import web
from aiohttp_admin2 import setup_admin

def create_app():
    app = web.Application()

    # setup admin interface
    setup_admin(app)

    return app
```
Then run with `adev runserver test.py` (you'll need to run from master though, current stable release is broken).

**Comment by Dreamsorcerer** [comment]
Seems to be the use of `ContexVar`. Would be a lot safer to just make the variable local to the class or similar, as we do in the other aio-libs libraries.

**Comment by Arfey** [comment]
> Would be a lot safer to just make the variable local to the class or similar, as we do in the other aio-libs libraries.

i need a global variable so use a ContexVar, but i'll think about it.

version aiohttp-admin2-0.0.5 from PyPI work for me. i'll try to use master tonight and find a problem.

**Comment by Arfey** [comment]
```
pip freeze | grep aiohttp 
  
aiohttp==3.8.1
aiohttp-admin2==0.0.5
aiohttp-devtools==0.13.1
aiohttp-jinja2==1.5
```

`app.py`

```
from aiohttp import web
from aiohttp_admin2 import setup_admin


def create_app():
    app = web.Application()

    # setup admin interface
    setup_admin(app)

    return app
```

`adev runserver app.py -p 8080`

work fine

after install from source code

```
pip freeze | grep aiohttp 

aiohttp==3.8.1
-e git+ssh://git@github.com/Arfey/aiohttp_admin2.git@2b3782389ec9e25809635811b76ef8111b27d8ba#egg=aiohttp_admin2
aiohttp-devtools==0.13.1
aiohttp-jinja2==1.5
```

all work fine.

version of python Python 3.9.8. Could u please give your python version.

**Comment by Dreamsorcerer** [comment]
Not sure what specific change makes the difference, but I only get the problem on master of devtools. Current stable release is really old and totally broken at this point. I'll try and test through some of the commits.

**Comment by Dreamsorcerer** [comment]
This is the change which makes the difference: https://github.com/aio-libs/aiohttp-devtools/commit/dc8240fc21c7a478faa0d86a1cac21eae2c68513

I'm not sure exactly why, maybe `loop.run_until_complete()` triggers a new context?

I'm not really sure what the point of `ContextVar` even is for this global. It appears to set the value when the app is configured and then just reads it throughout the code. I don't see how that usage is supposed to be context-sensitive..

**Comment by Arfey** [comment]
>It appears to set the value when the app is configured and then just reads it throughout the code. I don't see how that usage is supposed to be context-sensitive..

I have solved the problem with multiple admin interface for single app. In this case simple global variables are not fit and we can to solve that via `ContextVar`

>I'm not sure exactly why, maybe loop.run_until_complete() triggers a new context?

I'm not sure

**Comment by Arfey** [comment]
>I'm not sure exactly why, maybe loop.run_until_complete() triggers a new context?
```
  1 import asyncio                                                                  
  2 from contextvars import ContextVar                                              
  3                                                                                 
  4                                                                                 
  5 context = ContextVar('context', default='no_set')                               
  6                                                                                 
  7                                                                                 
  8 async def set_context():                                                        
  9     context.set('set_value')                                                    
 10                                                                                 
 11                                                                                 
 12 async def print_context():                                                      
 13     print(context.get())                                                        
 14                                                                                 
 15                                                                                 
 16 async def first_function():                                                     
 17     await set_context()                                                         
 18     await print_context()                                                       
 19                                                                                 
 20                                                                                 
 21 async def second_function():                                                    
 22     await print_context()                                                       
 23                                                                                 
 24                                                                                 
 25 loop = asyncio.get_event_loop()                                                 
 26 loop.run_until_complete(first_function())                                       
 27 loop.run_until_complete(second_function())                                      
 28    
 ```
result
```
set_value
no_set
```

So yes, it triggers a new context.

I think so, we can to solve current problem on `aiohttp-devtools` side, @Dreamsorcerer what do u think?

**Comment by Dreamsorcerer** [comment]
> > It appears to set the value when the app is configured and then just reads it throughout the code. I don't see how that usage is supposed to be context-sensitive..
> 
> I have solved the problem with multiple admin interface for single app. In this case simple global variables are not fit and we can to solve that via `ContextVar`

Multiple admins should be represented as multiple `web.Application` objects, I don't think using `ContextVar` makes sense for this. There really is never a need for mutable globals, if the state is simply stored as an instance attribute or on the `web.Application` object, then it would work perfectly, and all the state is nicely encapsulated within the subapp.

**Comment by Arfey** [comment]
`ContextVar` help me to avoid of using `web.Application` (and aiohttp) in core `aiohttp_admin`. Also, i don't want drilling params throw methods with `web.Application` instance for share some property

I totally agree with u that `ContextVar` is not perfect solution here but it works and work correct. In my opinion, i can quick fix problem in `aiohttp-devtools` and rewrite solution with `ContextVar` later. Or do u think that it's critical problem?

**Comment by Dreamsorcerer** [comment]
See https://github.com/Arfey/aiohttp_admin2/issues/5#issuecomment-1421389241
