### ISSUE TITLE
Read_only_fields in PostgresController

### ISSUE THREAD

**Issue by KondratevAD** [Arfey/aiohttp_admin2#8]
## Long story short

Hi, I found that read_only_fields does not work as stated in the [documentation](https://aiohttp-admin2.readthedocs.io/usage_aiohttp_admin.html#fields:~:text=detail%20settings-,read_only_fields,-(default%20%5B%5D)%20%2D%20list)

## Expected behaviour

In the admin dashboard, field that is specified in read_only_fields should become read-only

## Actual behaviour

The field remains changeable

## Your environment

* aiohttp_admin2 version: 0.0.5
* aiohttp version: 3.8.3
* Python version: 3.8.10
* Operating System: Linux

**Comment by Arfey** [comment]
Sorry, I realized late that you are Russian. Please don't use current open source software.

**Comment by imressed** [comment]
> > Sorry, I realized late that you are Russian. Please don't use current open source software.
> > thx
> 
> Sorry, I`m not understanding you. Why?

@KondratevAD Hto ne skache, toy moskal.

**Comment by bmwant** [comment]
@KondratevAD russia parasha

**Comment by KondratevAD** [comment]
> > > Sorry, I realized late that you are Russian. Please don't use current open source software.
> > > thx
> > 
> > 
> > Sorry, I`m not understanding you. Why?
> 
> @KondratevAD Hto ne skache, toy moskal.

And why did you decide that all the residents of Russia support all this? I am very sorry for you, you have a very good project. if you don't want to develop it, well, that's up to you. thank you at least for do this

**Comment by Arfey** [comment]
@KondratevAD i wanna develop this project and i will do but without people from Russia. No mater that all or not all the residents of Russia support WAR. If i will support u i will support your country. No, thanks.

good luck!

**Comment by KondratevAD** [comment]
> good luck!

Ok, thanks for that too

**Comment by KondratevAD** [comment]
thanks
